secret_key: wowchangeme
admin_password: youhavethepower
rooms:
  default:
    word_list: Default
  testing:
    word_list: Default
    params:
      round_time: 30
      score_time: 2
      min_player_count: 2